### ISSUE TITLE
THere is a P somewhere

### ISSUE THREAD

**Issue by pablocm90** [Pil0u/ruby-snake#1]
THere is a p somewhere that makes my terminal want to kill itself 

![image](https://user-images.githubusercontent.com/24973905/121320020-12142500-c90d-11eb-8d88-08970dc37631.png)
 

:D

**Comment by pil0u** [comment]
Solved with https://github.com/pil0u/ruby-snake/commit/3bfb66652ae33ef175e0f25a628e4330f1bc0bf8 :+1:
